name: Merge Branches

on:
  push:
    branches:
      - release/**

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Merge branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          branch_name=$(echo $GITHUB_REF | sed -e's|^refs/heads/release/||')
          python .github/scripts/merge_branches.py master release/$branch_name
          python .github/scripts/merge_branches.py develop master
          python .github/scripts/merge_branches.py feature/* develop 
