name: Merge Branches

on:
  push:
    branches:
      - release/**

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录以支持合并操作

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Get pushed release branch
        id: get_branch
        run: echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Merge release to master
        run: |
          python .github/scripts/merge_branches.py master release/${RELEASE_BRANCH}

      - name: Merge master to develop
        run: |
          python .github/scripts/merge_branches.py develop master

      - name: Merge develop to all feature branches
        run: |
          python .github/scripts/merge_branches.py --source develop --target feature/* 
