name: Sync Master to Develop and Feature Branches

# 控制工作流何时运行
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保获取所有的历史记录

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge master into develop
      if: github.ref == 'refs/heads/master'
      run: |
        git checkout develop
        git merge master --no-edit || (git merge --abort && echo "Merge conflict detected in develop branch, aborting merge." && exit 1)
        git push origin develop

    - name: Merge master into feature branches
      if: github.ref == 'refs/heads/master'
      run: |
        for branch in $(git branch -r | grep 'origin/feature/' | sed 's|origin/||'); do
          git checkout $branch
          if ! git merge master --no-edit; then
            git merge --abort
            echo "Merge conflict detected in branch $branch, aborting merge."
            continue
          fi
          git push origin $branch
        done
